In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("/content/Retail_Dataset_Cleaned (1).csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [9]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   object
 1   Store_Name             5146 non-null   object
 2   Brand_Name             5146 non-null   object
 3   Store_Type             5146 non-null   object
 4   City                   5146 non-null   object
 5   City_Tier              5146 non-null   object
 6   Product_Name           5146 non-null   object
 7   Category               5146 non-null   object
 8   Sub_Category           5146 non-null   object
 9   Product_Stage          5146 non-null   object
 10  Quantity_Available     5146 non-null   float64
 11  Units_Sold             5146 non-null   float64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   float64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   object
 20  Sales_Channel          5146 non-null   object
 21  Payment_Method         5146 non-null   object
 22  Supplier               5146 non-null   object
 23  Supplier_Rating        5146 non-null   object
 24  Promotion_Type         5146 non-null   object
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   object
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   object
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   object
 40  Weather_Impact         5146 non-null   object
 41  Delivery_Time          5146 non-null   float64
 42  Shipping_Cost          5146 non-null   float64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   object
 46  Season                 5146 non-null   object
dtypes: float64(15), int64(10), object(22)
memory usage: 1.8+ MB

In [11]:
df.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [12]:
category_revenue = pd.pivot_table(
    df,
    values="Revenue",
    index="Category",
    aggfunc="sum"
)

category_revenue

                      Revenue
Category
Clothes          2.220630e+08
Electronics      3.623063e+09
Gadgets          2.654379e+09
Groceries        2.394028e+07
Home Appliances  5.584119e+08

In [13]:
city_sales = pd.pivot_table(
    df,
    values="Units_Sold",
    index="City",
    aggfunc="sum"
)
city_sales

               Units_Sold
City
Ahmedabad          9784.0
Bangalore         24384.0
Bhopal             4216.0
Chennai           23674.0
Delhi             52516.0
Hyderabad         22449.0
Jaipur             9909.0
Kanpur             3419.0
Lucknow            3530.0
Mumbai            46679.0
Nagpur             4182.0
Pune              11115.0
Surat              8859.0
Visakhapatnam      3767.0

In [14]:
segment_revenue = pd.pivot_table(
    df,
    values="Revenue",
    index="Customer_Segment",
    aggfunc="sum"
)

segment_revenue

                       Revenue
Customer_Segment
Budget            1.712615e+09
Luxury            1.863606e+09
Mid-Range         1.822548e+09
Premium           1.683088e+09

In [15]:
category_summary = pd.pivot_table(
    df,
    values="Revenue",
    index="Category",
    aggfunc=["sum", "mean", "max", "min"]
)

category_summary

                          sum          mean         max       min
                      Revenue       Revenue     Revenue   Revenue
Category
Clothes          2.220630e+08  1.717425e+05   1245972.0    4985.0
Electronics      3.623063e+09  2.769926e+06  11182353.0  120655.0
Gadgets          2.654379e+09  2.594701e+06  23343582.0    9295.0
Groceries        2.394028e+07  2.365641e+04    350176.0     840.0
Home Appliances  5.584119e+08  1.094925e+06   6588592.0   81333.0

In [16]:
channel_summary = pd.pivot_table(
    df,
    values="Units_Sold",
    index="Sales_Channel",
    aggfunc=["sum", "mean"]
)

channel_summary

                                    sum       mean
                             Units_Sold Units_Sold
Sales_Channel
Brandx_India App                45472.0  44.190476
Brandx_India Online             44598.0  43.982249
Brandx_India Phone Order        44919.0  44.342547
Brandx_India Social Commerce    44695.0  45.329615
Brandx_India Store              48799.0  44.201993

In [17]:
city_performance = pd.pivot_table(
    df,
    values=["Revenue", "Profit_Margin"],
    index="City",
    aggfunc={
        "Revenue": "sum",
        "Profit_Margin": "mean"
    }
)
city_performance

               Profit_Margin       Revenue
City
Ahmedabad          22.624845  2.655276e+08
Bangalore          22.830374  8.407997e+08
Bhopal             22.620614  1.079895e+08
Chennai            22.259758  7.419116e+08
Delhi              22.282928  1.661122e+09
Hyderabad          22.239853  6.597958e+08
Jaipur             22.326377  2.670945e+08
Kanpur             22.539515  8.430218e+07
Lucknow            22.070538  9.486221e+07
Mumbai             22.435763  1.674840e+09
Nagpur             22.342162  7.479879e+07
Pune               22.756934  2.936829e+08
Surat              22.883691  2.340634e+08
Visakhapatnam      22.574245  8.106636e+07

In [18]:
Profit_Margin = pd.pivot_table(
    df,
    index="Profit_Margin",
    values="Store_Name",
    aggfunc="sum"
)

Profit_Margin

                                      Store_Name
Profit_Margin
14.68                Brandx_India Express Mumbai
14.81                  Brandx_India Daily Kanpur
14.84             Brandx_India Express Hyderabad
14.87             Brandx_India Express Hyderabad
14.91                Brandx_India Express Mumbai
...                                          ...
30.02             Brandx_India Fashion Bangalore
30.03               Brandx_India Daily Hyderabad
30.04                  Brandx_India Fresh Nagpur
30.11                  Brandx_India Express Pune
30.43          Brandx_India Superstore Bangalore

[1467 rows x 1 columns]

In [19]:
store_summary = pd.pivot_table(
    df,
    values=["Revenue", "Units_Sold"],
    index="Store_Type",
    aggfunc="sum"
)

store_summary

                   Revenue  Units_Sold
Store_Type
Express       1.438936e+09     45493.0
Flagship      1.413566e+09     46443.0
Mall Store    1.492527e+09     47919.0
Online Hub    1.442170e+09     44442.0
Street Store  1.294659e+09     44186.0

In [20]:
city_revenue = pd.pivot_table(
    df,
    values="Revenue",
    index="City",
    aggfunc="sum"
)
city_revenue

                    Revenue
City
Ahmedabad      2.655276e+08
Bangalore      8.407997e+08
Bhopal         1.079895e+08
Chennai        7.419116e+08
Delhi          1.661122e+09
Hyderabad      6.597958e+08
Jaipur         2.670945e+08
Kanpur         8.430218e+07
Lucknow        9.486221e+07
Mumbai         1.674840e+09
Nagpur         7.479879e+07
Pune           2.936829e+08
Surat          2.340634e+08
Visakhapatnam  8.106636e+07

In [21]:
#2. find the highest unit sold per product stage
stage_units = pd.pivot_table(
    df,
    values="Units_Sold",
    index="Product_Stage",
    aggfunc="sum"
)
stage_units

               Units_Sold
Product_Stage
Declining         45323.0
Discontinued      44364.0
Growing           48593.0
Mature            44659.0
New Launch        45544.0

In [22]:
#3. find categorywise totalrevenue , maximum unit sold and average unit price
category_analysis =  pd.pivot_table(
    df,
    values=["Revenue", "Units_Sold", "Unit_Price"],
    index="Category",
    aggfunc={
        "Revenue": "sum",
        "Units_Sold": "max",
        "Unit_Price": "mean"

    }
)
category_analysis

                      Revenue    Unit_Price  Units_Sold
Category
Clothes          2.220630e+08   4834.819026        85.0
Electronics      3.623063e+09  69648.201070        91.0
Gadgets          2.654379e+09  71011.307918        91.0
Groceries        2.394028e+07    248.826087       154.0
Home Appliances  5.584119e+08  31447.423529        78.0